name: pub_updater
description: A Dart package which enables checking whether a package is up to date.
version: 0.4.0
repository: https://github.com/open-runtime/pub_updater
issue_tracker: https://github.com/VeryGoodOpenSource/pub_updater/issues
topics: [cli, pub, version]

environment:
  sdk: '>=3.3.0 <4.5.0'

dependencies:
  http: ^1.1.0
  json_annotation: ^4.9.0
  process: ^5.0.2
  pub_semver: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^5.1.0
