name: pub_updater
description: A Dart package which enables checking whether a package is up to date.
version: 0.3.1
homepage: https://github.com/VeryGoodOpenSource/pub_updater

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1
  process: ^5.0.0
  pub_semver: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.0.0+1
